import cat1 from './assets/cat1.jpg';
import cat2 from './assets/cat2.jpg';
import cat3 from './assets/cat3.jpg';
import dog1 from './assets/dog1.jpg';
import dog2 from './assets/dog2.jpg';
import dog3 from './assets/dog3.jpg';

export const petsList = [
    {
        id: 1,
        type: 'dog',
        img: dog1,
        breed: 'Labrador',
        age: 12,
        gender: 'male',
        dogCompatible: 'yes',
        catCompatible: 'yes',
        childCompatible: 'yes',
        ownerName: 'Lionel Messi',
        ownerEmail: 'lm10@gmail.com',
        description: 'I love my pet so much she is very friendly',
    },
    {
        id: 2,
        type: 'dog',
        img: dog2,
        breed: 'German Shepherd',
        age: 8,
        gender: 'female',
        dogCompatible: 'yes',
        catCompatible: 'no',
        childCompatible: 'yes',
        ownerName: 'Virginia Woolf',
        ownerEmail: 'virginia.woolf@gmail.com',
        description: 'An intelligent and protective dog, great with kids and families.',
    },
    {
        id: 3,
        type: 'dog',
        img: dog3,
        breed: 'Beagle',
        age: 4,
        gender: 'male',
        dogCompatible: 'yes',
        catCompatible: 'yes',
        childCompatible: 'yes',
        ownerName: 'Mark Twain',
        ownerEmail: 'mark.twain@gmail.com',
        description: 'A friendly and curious dog, loves to explore and go on adventures.',
    },
    {
        id: 4,
        type: 'cat',
        img: cat1,
        breed: 'Siamese',
        age: 3,
        gender: 'female',
        dogCompatible: 'no',
        catCompatible: 'yes',
        childCompatible: 'yes',
        ownerName: 'Gabriel García Márquez',
        ownerEmail: 'gabriel.garcia@gmail.com',
        description: 'A playful and vocal cat, loves to cuddle and be around people.',
    },
    {
        id: 5,
        type: 'cat',
        img: cat2,
        breed: 'Persian',
        age: 5,
        gender: 'male',
        dogCompatible: 'no',
        catCompatible: 'yes',
        childCompatible: 'no',
        ownerName: 'Jane Austen',
        ownerEmail: 'jane.austen@gmail.com',
        description: 'A calm and affectionate cat, enjoys lounging around and being pampered.',
    },
    {
        id: 6,
        type: 'cat',
        img: cat3,
        breed: 'Maine Coon',
        age: 2,
        gender: 'female',
        dogCompatible: 'yes',
        catCompatible: 'yes',
        childCompatible: 'yes',
        ownerName: 'Albert Einstein',
        ownerEmail: 'albert.einstein@gmail.com',
        description: 'Friendly and sociable, loves to play with other pets and kids.',
    },
];
